apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-deployment
spec:
  selector:
    matchLabels:
      app: content
  template:
    metadata:
      labels:
        app: content
    spec:
      containers:
      - name: content
        image: gcr.io/cosmic-inkwell-398614/contant:1.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8001
