apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: gcr.io/cosmic-inkwell-398614/notification:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8002
