// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/muhammedarifp/user/api"
	"github.com/muhammedarifp/user/api/handlers"
	"github.com/muhammedarifp/user/config"
	"github.com/muhammedarifp/user/db"
	"github.com/muhammedarifp/user/repository"
	"github.com/muhammedarifp/user/usecases"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userUseCase := usecases.NewUserUseCase(userRepository)
	userHandler := handlers.NewUserHandler(userUseCase)
	adminRepository := repository.NewAdminRepository(gormDB)
	adminUsecase := usecases.NewAdminUsecase(adminRepository)
	adminHandler := handlers.NewAdminHandler(adminUsecase)
	serverHTTP := api.NewServerHTTP(userHandler, adminHandler)
	return serverHTTP, nil
}
