// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/muhammedarifp/tech-exchange/notification/api"
	"github.com/muhammedarifp/tech-exchange/notification/api/handlers"
	"github.com/muhammedarifp/tech-exchange/notification/config"
	"github.com/muhammedarifp/tech-exchange/notification/db"
	"github.com/muhammedarifp/tech-exchange/notification/repository"
	"github.com/muhammedarifp/tech-exchange/notification/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	notificationRepo := repository.NewNotificationRepo(gormDB)
	notificationUsecase := usecase.NewNotificationUseCase(notificationRepo)
	notificationsHandler := handlers.NewNotificationHandler(notificationUsecase)
	serverHTTP := api.NewServeHTTP(notificationsHandler)
	return serverHTTP, nil
}
