// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/muhammedarifp/tech-exchange/payments/api"
	"github.com/muhammedarifp/tech-exchange/payments/api/handlers"
	"github.com/muhammedarifp/tech-exchange/payments/config"
	"github.com/muhammedarifp/tech-exchange/payments/db"
	"github.com/muhammedarifp/tech-exchange/payments/repository"
	"github.com/muhammedarifp/tech-exchange/payments/usecase"
)

// Injectors from wire.go:

func InitWire(cfg config.Config) (*api.ServeHTTP, error) {
	gormDB, err := db.ConnectDatabase()
	if err != nil {
		return nil, err
	}
	userPaymentRepo := repository.NewUserPaymentRepo(gormDB)
	userPaymentUsecase := usecase.NewUserPaymentUsecase(userPaymentRepo)
	userPaymentHandler := handlers.NewUserPaymentHandler(userPaymentUsecase)
	adminPaymentRepo := repository.NewAdminPaymentDb(gormDB)
	adminPaymentUsecase := usecase.NewAdminPaymentsUsecase(adminPaymentRepo)
	adminPaymentHandler := handlers.NewAdminPaymentHandler(adminPaymentUsecase)
	serveHTTP := api.NewServeHTTP(userPaymentHandler, adminPaymentHandler)
	return serveHTTP, nil
}
